version: '3'

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: 'spreadsheet'
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spreadsheet